/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

/**
 *
 * @author Asghar Qambar Rizvi
 */
public class AdminAddNew extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddNew
     */
    static String username;
    public AdminAddNew(String userName) {
        initComponents();
        this.username=userName;
        setExtendedState(MAXIMIZED_BOTH);
        //EnableManageButton();
    }
    class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    private void EnableManageButton(){
                String rank = "";
           try {
               // Load the SQL Server JDBC driver
               Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

               try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                    CallableStatement cstmt = conn.prepareCall("{call ReturnRankOfAdmin(?)}")) {

                   cstmt.setString(1, username);

                   // Execute the stored procedure
                   try (ResultSet rs = cstmt.executeQuery()) {
                       // Check if there is a result
                       if (rs.next()) {
                           rank = rs.getString("AdminLevel");
                       }
                   }
               }
           } catch (Exception e) {
               // Handle exceptions
               JOptionPane.showMessageDialog(null, e.getMessage());
           }
           if (rank.equalsIgnoreCase("Super")){
               btn_manageAdmin.setVisible(true);
           }
           else
               btn_manageAdmin.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new JpanelGradient();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl_exit4 = new javax.swing.JLabel();
        lbl_addBus = new javax.swing.JLabel();
        lbl_addDriver = new javax.swing.JLabel();
        lbl_addRoute = new javax.swing.JLabel();
        lbl_addEmployee = new javax.swing.JLabel();
        lbl_addSchedule = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_addAdmin2 = new javax.swing.JLabel();
        lbl_hompage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_addAdmin3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_addAdmin4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_addAdmin5 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbl_addAdmin6 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btn_manageAdmin = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new JpanelGradient();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_adminName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/bus.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/delivery.png"))); // NOI18N
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/division.png"))); // NOI18N
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/driver.png"))); // NOI18N
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/logout.png"))); // NOI18N
        jLabel38.setText("jLabel6");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/schedule.png"))); // NOI18N
        jLabel39.setText("jLabel7");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_exit4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_exit4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit4.setText("       E X I T");
        lbl_exit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseExited(evt);
            }
        });

        lbl_addBus.setBackground(new Color(0,0,0,0 ));
        lbl_addBus.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addBus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addBus.setText("ADD A BUS");
        lbl_addBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseExited(evt);
            }
        });

        lbl_addDriver.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addDriver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addDriver.setText("ADD A DRIVER");
        lbl_addDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseExited(evt);
            }
        });

        lbl_addRoute.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addRoute.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addRoute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addRoute.setText("ADD A ROUTE");
        lbl_addRoute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseExited(evt);
            }
        });

        lbl_addEmployee.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addEmployee.setText("ADD EMPLOYEE");
        lbl_addEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseExited(evt);
            }
        });

        lbl_addSchedule.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addSchedule.setText("ADD SCHEDULE");
        lbl_addSchedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/administrator.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin2.setText("ADD  ADMIN");
        lbl_addAdmin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseExited(evt);
            }
        });

        lbl_hompage.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_hompage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hompage.setText(" H O M E   P A G E");
        lbl_hompage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_hompage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/homepage.png"))); // NOI18N
        jLabel9.setText("jLabel7");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin3.setText("     VIEW PASSENGERS");
        lbl_addAdmin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/passenger.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin4.setText("     RESERVATIONS");
        lbl_addAdmin4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/reservation.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin5.setText("USER QUERIES");
        lbl_addAdmin5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseExited(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/query.png"))); // NOI18N
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin6.setText("FEEDBACKS");
        lbl_addAdmin6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseExited(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/feedback.png"))); // NOI18N
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbl_hompage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_addAdmin6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addAdmin5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_hompage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_addAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbl_addAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(lbl_addAdmin5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel38))
                    .addComponent(lbl_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        btn_manageAdmin.setBackground(new java.awt.Color(0, 153, 153));
        btn_manageAdmin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_manageAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btn_manageAdmin.setText("M A N A G E   O T H E R   A D M I N S");
        btn_manageAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_manageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btn_manageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 660, 450, 40));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("          ADD A NEW ADMIN TO THE SYSTEM");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 830, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("E N T E R   R E C O R D");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 260, 40));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("E N T E R  P A S S W O R D:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 300, -1));

        txt_adminName.setBackground(new Color(0,0,0,0));
        txt_adminName.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_adminName.setForeground(new java.awt.Color(255, 255, 255));
        txt_adminName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_adminName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_adminNameKeyTyped(evt);
            }
        });
        jPanel2.add(txt_adminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 330, 40));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("E N T E R   U S E R N A M E :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 320, -1));

        txt_password.setBackground(new Color(0,0,0,0));
        txt_password.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 330, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 520, 460));

        lbl_bg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String name = txt_adminName.getText();
        String pass = txt_password.getText();

        // Check if any field is empty
        if (name.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
        } else {
            try {
                // Connect to the database
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                     CallableStatement cstmtExist = conn.prepareCall("{call CheckIfAdminExist(?, ?)}");
                     CallableStatement cstmtInsert = conn.prepareCall("{call InsertIntoAdmin(?, ?,?)}")) {

                    // Check if the admin already exists
                    cstmtExist.setString(1, name);
                    cstmtExist.setString(2, pass);
                    ResultSet rs = cstmtExist.executeQuery();
                    rs.next();
                    int count = rs.getInt(1);
                    if (count > 0) {
                        JOptionPane.showMessageDialog(null, "Admin already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                        txt_adminName.setText("");
                        txt_password.setText("");
                    } else {
                        // Insert the admin into the database
                        cstmtInsert.setString(1, name);
                        cstmtInsert.setString(2, pass);
                        cstmtInsert.setString(3, "Sub");
                        int rowsInserted = cstmtInsert.executeUpdate();
                        if (rowsInserted > 0) {
                            JOptionPane.showMessageDialog(null, "Admin added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "Failed to add admin", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_manageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageAdminActionPerformed
        AdminManage man =new AdminManage(username);
        man.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_manageAdminActionPerformed

    private void txt_adminNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_adminNameKeyTyped
       char c = evt.getKeyChar();
        if (Character.isDigit(c) || txt_adminName.getText().length() >= 100) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Error: Name cannot contain digits");
        }
    }//GEN-LAST:event_txt_adminNameKeyTyped

    private void lbl_exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseClicked
        HOMEPAGE home=new HOMEPAGE();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_exit4MouseClicked

    private void lbl_exit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseEntered
        lbl_exit4.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseEntered

    private void lbl_exit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseExited
        lbl_exit4.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseExited

    private void lbl_addBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseClicked
        AdminAddBus addBus=new AdminAddBus(username);
        addBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addBusMouseClicked

    private void lbl_addBusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseEntered
        lbl_addBus.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addBusMouseEntered

    private void lbl_addBusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseExited
        lbl_addBus.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addBusMouseExited

    private void lbl_addDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseClicked
        AdminAddDriver addDriver=new AdminAddDriver(username);
        addDriver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addDriverMouseClicked

    private void lbl_addDriverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseEntered
        lbl_addDriver.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addDriverMouseEntered

    private void lbl_addDriverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseExited
        lbl_addDriver.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addDriverMouseExited

    private void lbl_addRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseClicked
        AdminAddRoute addRoute = new AdminAddRoute(username);
        addRoute.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addRouteMouseClicked

    private void lbl_addRouteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseEntered
        lbl_addRoute.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addRouteMouseEntered

    private void lbl_addRouteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseExited
        lbl_addRoute.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addRouteMouseExited

    private void lbl_addEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseClicked
        AdminAddEmploye addEmp=new AdminAddEmploye(username);
        addEmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addEmployeeMouseClicked

    private void lbl_addEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseEntered
        lbl_addEmployee.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addEmployeeMouseEntered

    private void lbl_addEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseExited
        lbl_addEmployee.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addEmployeeMouseExited

    private void lbl_addScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseClicked
        AdminAddSch addSch = new AdminAddSch(username);
        addSch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addScheduleMouseClicked

    private void lbl_addScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseEntered
        lbl_addSchedule.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addScheduleMouseEntered

    private void lbl_addScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseExited
        lbl_addSchedule.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addScheduleMouseExited

    private void lbl_addAdmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseClicked
        AdminAddNew addAdmin = new AdminAddNew(username);
        addAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin2MouseClicked

    private void lbl_addAdmin2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseEntered
        lbl_addAdmin2.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin2MouseEntered

    private void lbl_addAdmin2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseExited
        lbl_addAdmin2.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin2MouseExited

    private void lbl_hompageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseClicked
        AdminHome home= new AdminHome(username);
        home.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_lbl_hompageMouseClicked

    private void lbl_hompageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseEntered
        lbl_hompage.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_hompageMouseEntered

    private void lbl_hompageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseExited
        lbl_hompage.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_hompageMouseExited

    private void lbl_addAdmin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseClicked
        AdminViewPass pass=new AdminViewPass(username);
        pass.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin3MouseClicked

    private void lbl_addAdmin3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseEntered
        lbl_addAdmin3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin3MouseEntered

    private void lbl_addAdmin3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseExited
        lbl_addAdmin3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin3MouseExited

    private void lbl_addAdmin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseClicked
        AdminViewReser res = new AdminViewReser(username);
        res.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin4MouseClicked

    private void lbl_addAdmin4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseEntered
        lbl_addAdmin4.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin4MouseEntered

    private void lbl_addAdmin4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseExited
        lbl_addAdmin4.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin4MouseExited

    private void lbl_addAdmin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseClicked
        AdminViewUserQueries query=new AdminViewUserQueries(username);
        query.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin5MouseClicked

    private void lbl_addAdmin5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseEntered
        lbl_addAdmin5.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin5MouseEntered

    private void lbl_addAdmin5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseExited
        lbl_addAdmin5.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin5MouseExited

    private void lbl_addAdmin6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseClicked
        AdminViewFeedback feed=new AdminViewFeedback(username);
        feed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin6MouseClicked

    private void lbl_addAdmin6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseEntered
        lbl_addAdmin6.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin6MouseEntered

    private void lbl_addAdmin6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseExited
        lbl_addAdmin6.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddNew(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_manageAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_addAdmin2;
    private javax.swing.JLabel lbl_addAdmin3;
    private javax.swing.JLabel lbl_addAdmin4;
    private javax.swing.JLabel lbl_addAdmin5;
    private javax.swing.JLabel lbl_addAdmin6;
    private javax.swing.JLabel lbl_addBus;
    private javax.swing.JLabel lbl_addDriver;
    private javax.swing.JLabel lbl_addEmployee;
    private javax.swing.JLabel lbl_addRoute;
    private javax.swing.JLabel lbl_addSchedule;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_exit4;
    private javax.swing.JLabel lbl_hompage;
    private javax.swing.JTextField txt_adminName;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
