/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asghar Qambar Rizvi
 */
public class AdminAddDriver extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddDriver
     */
    static String username;
    public AdminAddDriver(String username) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.username=username;
        UnassignedBuses();
        display();
        
    }
    class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    private void UnassignedBuses(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn= DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=Mydatabase;encrypt=true;trustServerCertificate=true","admin","123456");
            CallableStatement cs = conn.prepareCall("{call DisplayUnassignedBuses}");
            ResultSet rs = cs.executeQuery();
            
            while (rs.next()) {
                String busnumber = rs.getString("BusNumber");
                cmb_bs.addItem(busnumber);
    }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    public void display() {
            String connectionString = "jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true";
try (Connection connection = DriverManager.getConnection(connectionString, "admin", "123456")) {
    String sql = "{call DisplayDrivers()}"; // Call the stored procedure
    try (CallableStatement statement = connection.prepareCall(sql)) {
        try (ResultSet rs = statement.executeQuery()) {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("DriverID");
            model.addColumn("BusNumber");
            model.addColumn("Name");
            model.addColumn("License_Number");
            model.addColumn("Contact");

            // Add rows to the model
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("DriverID"),
                    rs.getString("BusNumber"),
                    rs.getString("Name"),
                    rs.getString("License_number"), // Note: column name is case-sensitive
                    rs.getString("Contact")
                });
            }

            table_Display.setModel(model);
            CustomHeaderRenderer renderer = new CustomHeaderRenderer();
        for (int i = 0; i < 5; i++) {
          table_Display.getColumnModel().getColumn(i).setHeaderRenderer(renderer);
            }
        }
    }
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

          }

        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_Display = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_DELETE = new javax.swing.JButton();
        jPanel2 = new JpanelGradient();
        cmb_bs = new javax.swing.JComboBox<>();
        txt_driverid = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_lic = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_contact = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new JpanelGradient();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl_exit4 = new javax.swing.JLabel();
        lbl_addBus = new javax.swing.JLabel();
        lbl_addDriver = new javax.swing.JLabel();
        lbl_addRoute = new javax.swing.JLabel();
        lbl_addEmployee = new javax.swing.JLabel();
        lbl_addSchedule = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_addAdmin2 = new javax.swing.JLabel();
        lbl_hompage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_addAdmin3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_addAdmin4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_addAdmin5 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbl_addAdmin6 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();
        lbl_bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_Display.setBorder(new javax.swing.border.MatteBorder(null));
        table_Display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DRIVER ID", "BUS NUMBER", "DRIVER NAME", "LICENSE NUMBER", "CONTACT NUMBER"
            }
        ));
        table_Display.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_Display.setFillsViewportHeight(true);
        table_Display.setRowHeight(25);
        table_Display.setSelectionBackground(new java.awt.Color(36, 136, 203));
        table_Display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_Display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_Display.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_Display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 910, 190));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("           A D D   A  D R I V E R");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 547, 80));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("E N T E R   D R I V E R   I D :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 250, 40));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("S E L E C T  A  B U S :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 300, -1));

        btn_DELETE.setBackground(new java.awt.Color(0, 153, 153));
        btn_DELETE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_DELETE.setForeground(new java.awt.Color(255, 255, 255));
        btn_DELETE.setText("D E L E T E");
        btn_DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 710, 260, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_bs.setBackground(new Color(0,0,0,0));
        cmb_bs.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmb_bs.setForeground(new java.awt.Color(255, 255, 255));
        cmb_bs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[-S E L E C T   A   B U S -]" }));
        cmb_bs.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(cmb_bs, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 330, 41));

        txt_driverid.setBackground(new Color(0,0,0,0));
        txt_driverid.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_driverid.setForeground(new java.awt.Color(255, 255, 255));
        txt_driverid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_driverid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_driveridActionPerformed(evt);
            }
        });
        txt_driverid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_driveridKeyPressed(evt);
            }
        });
        jPanel2.add(txt_driverid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 320, 40));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("E N T E R   N A M E   O F   D R I V E R :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 320, -1));

        txt_name.setBackground(new Color(0,0,0,0));
        txt_name.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nameKeyTyped(evt);
            }
        });
        jPanel2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 330, 40));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("E N T E R  L I C E N S E  N U M B E R :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 330, -1));

        txt_lic.setBackground(new Color(0,0,0,0));
        txt_lic.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_lic.setForeground(new java.awt.Color(255, 255, 255));
        txt_lic.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_lic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_licKeyTyped(evt);
            }
        });
        jPanel2.add(txt_lic, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 340, 40));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("E N T E R   R E C O R D");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 260, 40));

        txt_contact.setBackground(new Color(0,0,0,0));
        txt_contact.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_contact.setForeground(new java.awt.Color(255, 255, 255));
        txt_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        txt_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contactKeyTyped(evt);
            }
        });
        jPanel2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 340, 40));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("E N T E R  C O N T A C T  N U M B E R :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 330, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 1040, 320));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("U P D A T E");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 710, 260, 40));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/bus.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/delivery.png"))); // NOI18N
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/division.png"))); // NOI18N
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/driver.png"))); // NOI18N
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/logout.png"))); // NOI18N
        jLabel38.setText("jLabel6");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/schedule.png"))); // NOI18N
        jLabel39.setText("jLabel7");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_exit4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_exit4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit4.setText("       E X I T");
        lbl_exit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseExited(evt);
            }
        });

        lbl_addBus.setBackground(new Color(0,0,0,0 ));
        lbl_addBus.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addBus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addBus.setText("ADD A BUS");
        lbl_addBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseExited(evt);
            }
        });

        lbl_addDriver.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addDriver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addDriver.setText("ADD A DRIVER");
        lbl_addDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseExited(evt);
            }
        });

        lbl_addRoute.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addRoute.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addRoute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addRoute.setText("ADD A ROUTE");
        lbl_addRoute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseExited(evt);
            }
        });

        lbl_addEmployee.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addEmployee.setText("ADD EMPLOYEE");
        lbl_addEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseExited(evt);
            }
        });

        lbl_addSchedule.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addSchedule.setText("ADD SCHEDULE");
        lbl_addSchedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/administrator.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin2.setText("ADD  ADMIN");
        lbl_addAdmin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseExited(evt);
            }
        });

        lbl_hompage.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_hompage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hompage.setText(" H O M E   P A G E");
        lbl_hompage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_hompage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/homepage.png"))); // NOI18N
        jLabel9.setText("jLabel7");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin3.setText("     VIEW PASSENGERS");
        lbl_addAdmin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/passenger.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin4.setText("     RESERVATIONS");
        lbl_addAdmin4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/reservation.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin5.setText("USER QUERIES");
        lbl_addAdmin5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseExited(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/query.png"))); // NOI18N
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin6.setText("FEEDBACKS");
        lbl_addAdmin6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseExited(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/feedback.png"))); // NOI18N
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbl_hompage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_addAdmin6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addAdmin5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_hompage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_addAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbl_addAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(lbl_addAdmin5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel38))
                    .addComponent(lbl_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        lbl_bg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 3110, 930));

        lbl_bg1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bg1.setOpaque(true);
        getContentPane().add(lbl_bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 3110, 930));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String driverid=txt_driverid.getText(), contact=txt_contact.getText(), name=txt_name.getText(),  lic=txt_lic.getText();
        String busID= (String) cmb_bs.getSelectedItem();
        if (driverid.isEmpty() || contact.isEmpty() || name.isEmpty() || lic.isEmpty() || cmb_bs.getSelectedIndex() ==0) {
            JOptionPane.showMessageDialog(this, "FIELDS ARE EMPTY");
        }
        else{
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
             CallableStatement cstmt = conn.prepareCall("{call insertIntoDriver(?,?,?,?,?)}");
             cstmt.setString(1, driverid);
             cstmt.setString(2, busID);
             cstmt.setString(3, name);
             cstmt.setString(4, lic);
             cstmt.setString(5, contact);
             
             int rowsInserted = cstmt.executeUpdate();
             if (rowsInserted>=0) {
                 JOptionPane.showMessageDialog(this, "SUCCESSFULLY INSERTED");
                 txt_driverid.setText("");
            txt_contact.setText("");
            txt_name.setText("");
            txt_lic.setText("");
            cmb_bs.setSelectedIndex(0);
            display();
                 
            }
             else{
                 JOptionPane.showMessageDialog(this, "ERROR");
             }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_driveridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_driveridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_driveridActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        table_Display.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void btn_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DELETEActionPerformed
        if (table_Display.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "SELECT A ROW");
        } else {
            int selectedRowIndex = table_Display.getSelectedRow();
            if (selectedRowIndex != -1) {
                String col1Value = table_Display.getValueAt(selectedRowIndex, 0).toString();
                int driverid=Integer.parseInt(col1Value);
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                         CallableStatement cstmt = conn.prepareCall("{call DeleteDriverById (?)}")) {
                        cstmt.setInt(1, driverid);
                        int rows = cstmt.executeUpdate();
                        if (rows > 0) {
                            JOptionPane.showMessageDialog(this, "SUCCESSFULLY DELETED!!!");
                            display();
                        } else {
                            JOptionPane.showMessageDialog(this, "No rows deleted");
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_DELETEActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (table_Display.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "SELECT A ROW FIRST");
        }
        else{
            
            int selectedRowIndex = table_Display.getSelectedRow();
            String col1Value = table_Display.getValueAt(selectedRowIndex, 0).toString();
            String col2Value = table_Display.getValueAt(selectedRowIndex, 1).toString();
            String col3Value = table_Display.getValueAt(selectedRowIndex, 2).toString();
            String col4Value = table_Display.getValueAt(selectedRowIndex, 3).toString();
            String col5Value = table_Display.getValueAt(selectedRowIndex, 4).toString();
            UpdateDriver updDriver= new UpdateDriver(col1Value,col2Value,col3Value, col4Value, col5Value,username);
            updDriver.setVisible(true);
            
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_driveridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_driveridKeyPressed
    char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume(); // Ignore this event
        JOptionPane.showMessageDialog(null, "Error: Only integer values are allowed.");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_driveridKeyPressed

    private void txt_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyTyped
char c = evt.getKeyChar();
        if (Character.isDigit(c) || txt_name.getText().length() >= 100) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Error: Name cannot contain digits.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameKeyTyped

    private void txt_licKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_licKeyTyped
char c = evt.getKeyChar();
        if (txt_lic.getText().length() >= 50) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Error: License must contain less than 50 characters.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_licKeyTyped

    private void txt_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txt_contact.getText().length() >= 12) {
            evt.consume();
            if (txt_contact.getText().length() >= 12) {
                JOptionPane.showMessageDialog(null, "Error: Contact must be exactly 12 digits.");
            } else {
                JOptionPane.showMessageDialog(null, "Error: Contact must contain only digits.");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactKeyTyped

    private void lbl_exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseClicked
        HOMEPAGE home=new HOMEPAGE();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_exit4MouseClicked

    private void lbl_exit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseEntered
        lbl_exit4.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseEntered

    private void lbl_exit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseExited
        lbl_exit4.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseExited

    private void lbl_addBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseClicked
        AdminAddBus addBus=new AdminAddBus(username);
        addBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addBusMouseClicked

    private void lbl_addBusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseEntered
        lbl_addBus.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addBusMouseEntered

    private void lbl_addBusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseExited
        lbl_addBus.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addBusMouseExited

    private void lbl_addDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseClicked
        AdminAddDriver addDriver=new AdminAddDriver(username);
        addDriver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addDriverMouseClicked

    private void lbl_addDriverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseEntered
        lbl_addDriver.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addDriverMouseEntered

    private void lbl_addDriverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseExited
        lbl_addDriver.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addDriverMouseExited

    private void lbl_addRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseClicked
        AdminAddRoute addRoute = new AdminAddRoute(username);
        addRoute.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addRouteMouseClicked

    private void lbl_addRouteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseEntered
        lbl_addRoute.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addRouteMouseEntered

    private void lbl_addRouteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseExited
        lbl_addRoute.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addRouteMouseExited

    private void lbl_addEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseClicked
        AdminAddEmploye addEmp=new AdminAddEmploye(username);
        addEmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addEmployeeMouseClicked

    private void lbl_addEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseEntered
        lbl_addEmployee.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addEmployeeMouseEntered

    private void lbl_addEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseExited
        lbl_addEmployee.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addEmployeeMouseExited

    private void lbl_addScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseClicked
        AdminAddSch addSch = new AdminAddSch(username);
        addSch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addScheduleMouseClicked

    private void lbl_addScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseEntered
        lbl_addSchedule.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addScheduleMouseEntered

    private void lbl_addScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseExited
        lbl_addSchedule.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addScheduleMouseExited

    private void lbl_addAdmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseClicked
        AdminAddNew addAdmin = new AdminAddNew(username);
        addAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin2MouseClicked

    private void lbl_addAdmin2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseEntered
        lbl_addAdmin2.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin2MouseEntered

    private void lbl_addAdmin2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseExited
        lbl_addAdmin2.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin2MouseExited

    private void lbl_hompageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseClicked
        AdminHome home= new AdminHome(username);
        home.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_lbl_hompageMouseClicked

    private void lbl_hompageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseEntered
        lbl_hompage.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_hompageMouseEntered

    private void lbl_hompageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseExited
        lbl_hompage.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_hompageMouseExited

    private void lbl_addAdmin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseClicked
        AdminViewPass pass=new AdminViewPass(username);
        pass.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin3MouseClicked

    private void lbl_addAdmin3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseEntered
        lbl_addAdmin3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin3MouseEntered

    private void lbl_addAdmin3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseExited
        lbl_addAdmin3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin3MouseExited

    private void lbl_addAdmin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseClicked
        AdminViewReser res = new AdminViewReser(username);
        res.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin4MouseClicked

    private void lbl_addAdmin4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseEntered
        lbl_addAdmin4.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin4MouseEntered

    private void lbl_addAdmin4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseExited
        lbl_addAdmin4.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin4MouseExited

    private void lbl_addAdmin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseClicked
        AdminViewUserQueries query=new AdminViewUserQueries(username);
        query.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin5MouseClicked

    private void lbl_addAdmin5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseEntered
        lbl_addAdmin5.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin5MouseEntered

    private void lbl_addAdmin5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseExited
        lbl_addAdmin5.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin5MouseExited

    private void lbl_addAdmin6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseClicked
        AdminViewFeedback feed=new AdminViewFeedback(username);
        feed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin6MouseClicked

    private void lbl_addAdmin6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseEntered
        lbl_addAdmin6.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin6MouseEntered

    private void lbl_addAdmin6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseExited
        lbl_addAdmin6.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddDriver(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DELETE;
    private javax.swing.JComboBox<String> cmb_bs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_addAdmin2;
    private javax.swing.JLabel lbl_addAdmin3;
    private javax.swing.JLabel lbl_addAdmin4;
    private javax.swing.JLabel lbl_addAdmin5;
    private javax.swing.JLabel lbl_addAdmin6;
    private javax.swing.JLabel lbl_addBus;
    private javax.swing.JLabel lbl_addDriver;
    private javax.swing.JLabel lbl_addEmployee;
    private javax.swing.JLabel lbl_addRoute;
    private javax.swing.JLabel lbl_addSchedule;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_bg1;
    private javax.swing.JLabel lbl_exit4;
    private javax.swing.JLabel lbl_hompage;
    private javax.swing.JTable table_Display;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_driverid;
    private javax.swing.JTextField txt_lic;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
