/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asghar Qambar Rizvi
 */
public class AdminAddRoute extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddRoute
     */
    static String username;
    public AdminAddRoute(String username) {
        initComponents();setExtendedState(MAXIMIZED_BOTH);
        this.username=username;
        CustomHeaderRenderer renderer = new CustomHeaderRenderer();
        display();
         for (int i = 0; i < 5; i++) {
          table_Display.getColumnModel().getColumn(i).setHeaderRenderer(renderer);
           }
    }
class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    public void display() {
        String connectionString = "jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true";

try (Connection connection = DriverManager.getConnection(connectionString, "admin", "123456")) {
    String sql = "{call DisplayRoute()}"; // Call the stored procedure

    try (CallableStatement statement = connection.prepareCall(sql)) {
        try (ResultSet rs = statement.executeQuery()) {
            // Create a DefaultTableModel
            DefaultTableModel model = new DefaultTableModel();

            // Add columns to the model (assuming column names match the procedure output)
            model.addColumn("RouteId");
            model.addColumn("Source");
            model.addColumn("Destination");
            model.addColumn("Distance");
            model.addColumn("Duration");

            // Add rows to the model
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("RouteId"),
                    rs.getString("Source"),
                    rs.getString("Destination"),
                    rs.getString("Distance"),
                    rs.getString("Duration")
                });
            }

            table_Display.setModel(model);
        }
    }
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new JpanelGradient();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl_exit4 = new javax.swing.JLabel();
        lbl_addBus = new javax.swing.JLabel();
        lbl_addDriver = new javax.swing.JLabel();
        lbl_addRoute = new javax.swing.JLabel();
        lbl_addEmployee = new javax.swing.JLabel();
        lbl_addSchedule = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_addAdmin2 = new javax.swing.JLabel();
        lbl_hompage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_addAdmin3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_addAdmin4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_addAdmin5 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbl_addAdmin6 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btn_DELETE = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Display = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new JpanelGradient();
        jLabel17 = new javax.swing.JLabel();
        txt_dest = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_distance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_duration = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_source = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/bus.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/delivery.png"))); // NOI18N
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/division.png"))); // NOI18N
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/driver.png"))); // NOI18N
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/logout.png"))); // NOI18N
        jLabel38.setText("jLabel6");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/schedule.png"))); // NOI18N
        jLabel39.setText("jLabel7");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_exit4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_exit4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit4.setText("       E X I T");
        lbl_exit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseExited(evt);
            }
        });

        lbl_addBus.setBackground(new Color(0,0,0,0 ));
        lbl_addBus.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addBus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addBus.setText("ADD A BUS");
        lbl_addBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseExited(evt);
            }
        });

        lbl_addDriver.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addDriver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addDriver.setText("ADD A DRIVER");
        lbl_addDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseExited(evt);
            }
        });

        lbl_addRoute.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addRoute.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addRoute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addRoute.setText("ADD A ROUTE");
        lbl_addRoute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseExited(evt);
            }
        });

        lbl_addEmployee.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addEmployee.setText("ADD EMPLOYEE");
        lbl_addEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseExited(evt);
            }
        });

        lbl_addSchedule.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addSchedule.setText("ADD SCHEDULE");
        lbl_addSchedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/administrator.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin2.setText("ADD  ADMIN");
        lbl_addAdmin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseExited(evt);
            }
        });

        lbl_hompage.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_hompage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hompage.setText(" H O M E   P A G E");
        lbl_hompage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_hompage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/homepage.png"))); // NOI18N
        jLabel9.setText("jLabel7");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin3.setText("     VIEW PASSENGERS");
        lbl_addAdmin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/passenger.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin4.setText("     RESERVATIONS");
        lbl_addAdmin4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/reservation.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin5.setText("USER QUERIES");
        lbl_addAdmin5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseExited(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/query.png"))); // NOI18N
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin6.setText("FEEDBACKS");
        lbl_addAdmin6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseExited(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/feedback.png"))); // NOI18N
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbl_hompage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_addAdmin6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addAdmin5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_hompage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_addAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbl_addAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(lbl_addAdmin5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel38))
                    .addComponent(lbl_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        btn_DELETE.setBackground(new java.awt.Color(0, 153, 153));
        btn_DELETE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_DELETE.setForeground(new java.awt.Color(255, 255, 255));
        btn_DELETE.setText("D E L E T E");
        btn_DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DELETEActionPerformed(evt);
            }
        });
        getContentPane().add(btn_DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 710, 260, 40));

        btn_update.setBackground(new java.awt.Color(0, 153, 153));
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("U P D A T E ");
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 710, 260, 40));

        table_Display.setBorder(new javax.swing.border.MatteBorder(null));
        table_Display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ROUTE ID", "SOURCE", "DESTINATION", "DISTANCE", "DURATION"
            }
        ));
        table_Display.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_Display.setFillsViewportHeight(true);
        table_Display.setRowHeight(25);
        table_Display.setSelectionBackground(new java.awt.Color(36, 136, 203));
        table_Display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_Display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_Display.setShowGrid(true);
        table_Display.setShowVerticalLines(false);
        table_Display.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_Display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 980, 190));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("A D D   A  R O U T E");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 50, 380, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("E N T E R   D E S T I N A T I O N :");

        txt_dest.setBackground(new Color(0,0,0,0));
        txt_dest.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_dest.setForeground(new java.awt.Color(255, 255, 255));
        txt_dest.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_dest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_destKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("E N T E R   D I S T A N C E :");

        txt_distance.setBackground(new Color(0,0,0,0));
        txt_distance.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_distance.setForeground(new java.awt.Color(255, 255, 255));
        txt_distance.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_distanceActionPerformed(evt);
            }
        });
        txt_distance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_distanceKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("E N T E R   R E C O R D");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_duration.setBackground(new Color(0,0,0,0));
        txt_duration.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_duration.setForeground(new java.awt.Color(255, 255, 255));
        txt_duration.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_durationActionPerformed(evt);
            }
        });
        txt_duration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_durationKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("E N T E R  D U R A T I O N : ");

        txt_source.setBackground(new Color(0,0,0,0));
        txt_source.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_source.setForeground(new java.awt.Color(255, 255, 255));
        txt_source.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_source.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sourceKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("E N T E R  S O U R C E :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jLabel15)
                            .addComponent(txt_source)
                            .addComponent(txt_duration))
                        .addGap(216, 216, 216)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_distance, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dest))))
                .addGap(105, 105, 105))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txt_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_distance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 150, 1040, 290));

        lbl_bg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean isRouteExists(String source, String destination) throws Exception {
        boolean exists = false;
            try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                CallableStatement cstmt = conn.prepareCall("{call SourceDestinationAlreadyExist(?, ?)}")) {
                cstmt.setString(1, source);
                cstmt.setString(2, destination);
        
                // Execute the stored procedure
                boolean hasResults = cstmt.execute();

                // If the stored procedure returns a result set
                if (hasResults) {
                    try (ResultSet rs = cstmt.getResultSet()) {
                        if (rs.next()) {
                            int count = rs.getInt("countNo");
                            if (count > 0) {
                                exists = true;
                            }
                        }
                    }
                }
            }
    return exists;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String source = txt_source.getText();
            String destination = txt_dest.getText();
            String distanceStr = txt_distance.getText();
            String durationStr = txt_duration.getText();

            if (source.isEmpty() || destination.isEmpty() || distanceStr.isEmpty() || durationStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fields are Empty");
            } else {
                try {
                    // Convert distance and duration strings to float and int respectively
                    float distance = Float.parseFloat(distanceStr);
                    int duration = Integer.parseInt(durationStr);

                    // Check if the route already exists
                    if (isRouteExists(source, destination)) {
                        JOptionPane.showMessageDialog(this, "Route already exists!");
                    } else {
                        // Call the stored procedure insert_route
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                             CallableStatement cstmt = conn.prepareCall("{call insertRoute(?,?,?,?)}")) {
                            cstmt.setString(1, source);
                            cstmt.setString(2, destination);
                            cstmt.setFloat(3, distance);
                            cstmt.setInt(4, duration);

                            int rowsInserted = cstmt.executeUpdate();
                            if (rowsInserted > 0) {
                                JOptionPane.showMessageDialog(null, "Route has been inserted successfully!");
                                txt_source.setText("");
                            txt_dest.setText("");
                            txt_distance.setText("");
                            txt_duration.setText("");
                            display();
                            } else {
                                JOptionPane.showMessageDialog(null, "Insertion failed due to some error");
                            }
                        }
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid distance or duration format");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_durationActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if (table_Display.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "SELECT A ROW");
        }
        else{
            int selectedRowIndex = table_Display.getSelectedRow();
            String col1Value = table_Display.getValueAt(selectedRowIndex, 0).toString();
            String col2Value = table_Display.getValueAt(selectedRowIndex, 1).toString();
            String col3Value = table_Display.getValueAt(selectedRowIndex, 2).toString();
            String col4Value = table_Display.getValueAt(selectedRowIndex, 3).toString();
            String col5Value = table_Display.getValueAt(selectedRowIndex, 4).toString();
            UpdateRoute updateRoute = new UpdateRoute(col1Value, col2Value, col3Value, col4Value, col5Value);
            updateRoute.setVisible(true);
            
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        table_Display.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void txt_distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_distanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_distanceActionPerformed

    private void btn_DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DELETEActionPerformed
        if (table_Display.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "SELECT A ROW");
        } else {
            int selectedRowIndex = table_Display.getSelectedRow();
            if (selectedRowIndex != -1) {
                String col1Value = table_Display.getValueAt(selectedRowIndex, 0).toString();
                int route=Integer.parseInt(col1Value);
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                         CallableStatement cstmt = conn.prepareCall("{call deleteRoute (?)}")) {
                        cstmt.setInt(1, route);
                        int rows = cstmt.executeUpdate();
                        if (rows > 0) {
                            JOptionPane.showMessageDialog(this, "SUCCESSFULLY DELETED!!!");
                            display();
                        } else {
                            JOptionPane.showMessageDialog(this, "No rows deleted");
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_DELETEActionPerformed

    private void txt_sourceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sourceKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || txt_source.getText().length() >= 100) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Error: Source cannot contain digits");
        }
    }//GEN-LAST:event_txt_sourceKeyTyped

    private void txt_destKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_destKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c) || txt_dest.getText().length() >= 100) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Error: Destination cannot contain digits");
        }
    }//GEN-LAST:event_txt_destKeyTyped

    private void txt_durationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_durationKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txt_duration.getText().length() >= 12) {
            evt.consume();
         
                JOptionPane.showMessageDialog(null, "Error: Contact must contain only digits.");
            
        }   
    }//GEN-LAST:event_txt_durationKeyTyped

    private void txt_distanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_distanceKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txt_duration.getText().length() >= 12) {
            evt.consume();
         
                JOptionPane.showMessageDialog(null, "Error: Contact must contain only digits.");
            
        }  
    }//GEN-LAST:event_txt_distanceKeyTyped

    private void lbl_exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseClicked
        HOMEPAGE home=new HOMEPAGE();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_exit4MouseClicked

    private void lbl_exit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseEntered
        lbl_exit4.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseEntered

    private void lbl_exit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseExited
        lbl_exit4.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseExited

    private void lbl_addBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseClicked
        AdminAddBus addBus=new AdminAddBus(username);
        addBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addBusMouseClicked

    private void lbl_addBusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseEntered
        lbl_addBus.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addBusMouseEntered

    private void lbl_addBusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseExited
        lbl_addBus.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addBusMouseExited

    private void lbl_addDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseClicked
        AdminAddDriver addDriver=new AdminAddDriver(username);
        addDriver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addDriverMouseClicked

    private void lbl_addDriverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseEntered
        lbl_addDriver.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addDriverMouseEntered

    private void lbl_addDriverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseExited
        lbl_addDriver.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addDriverMouseExited

    private void lbl_addRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseClicked
        AdminAddRoute addRoute = new AdminAddRoute(username);
        addRoute.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addRouteMouseClicked

    private void lbl_addRouteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseEntered
        lbl_addRoute.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addRouteMouseEntered

    private void lbl_addRouteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseExited
        lbl_addRoute.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addRouteMouseExited

    private void lbl_addEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseClicked
        AdminAddEmploye addEmp=new AdminAddEmploye(username);
        addEmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addEmployeeMouseClicked

    private void lbl_addEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseEntered
        lbl_addEmployee.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addEmployeeMouseEntered

    private void lbl_addEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseExited
        lbl_addEmployee.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addEmployeeMouseExited

    private void lbl_addScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseClicked
        AdminAddSch addSch = new AdminAddSch(username);
        addSch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addScheduleMouseClicked

    private void lbl_addScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseEntered
        lbl_addSchedule.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addScheduleMouseEntered

    private void lbl_addScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseExited
        lbl_addSchedule.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addScheduleMouseExited

    private void lbl_addAdmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseClicked
        AdminAddNew addAdmin = new AdminAddNew(username);
        addAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin2MouseClicked

    private void lbl_addAdmin2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseEntered
        lbl_addAdmin2.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin2MouseEntered

    private void lbl_addAdmin2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseExited
        lbl_addAdmin2.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin2MouseExited

    private void lbl_hompageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseClicked
        AdminHome home= new AdminHome(username);
        home.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_lbl_hompageMouseClicked

    private void lbl_hompageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseEntered
        lbl_hompage.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_hompageMouseEntered

    private void lbl_hompageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseExited
        lbl_hompage.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_hompageMouseExited

    private void lbl_addAdmin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseClicked
        AdminViewPass pass=new AdminViewPass(username);
        pass.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin3MouseClicked

    private void lbl_addAdmin3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseEntered
        lbl_addAdmin3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin3MouseEntered

    private void lbl_addAdmin3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseExited
        lbl_addAdmin3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin3MouseExited

    private void lbl_addAdmin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseClicked
        AdminViewReser res = new AdminViewReser(username);
        res.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin4MouseClicked

    private void lbl_addAdmin4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseEntered
        lbl_addAdmin4.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin4MouseEntered

    private void lbl_addAdmin4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseExited
        lbl_addAdmin4.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin4MouseExited

    private void lbl_addAdmin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseClicked
        AdminViewUserQueries query=new AdminViewUserQueries(username);
        query.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin5MouseClicked

    private void lbl_addAdmin5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseEntered
        lbl_addAdmin5.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin5MouseEntered

    private void lbl_addAdmin5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseExited
        lbl_addAdmin5.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin5MouseExited

    private void lbl_addAdmin6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseClicked
        AdminViewFeedback feed=new AdminViewFeedback(username);
        feed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin6MouseClicked

    private void lbl_addAdmin6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseEntered
        lbl_addAdmin6.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin6MouseEntered

    private void lbl_addAdmin6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseExited
        lbl_addAdmin6.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddRoute(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DELETE;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_addAdmin2;
    private javax.swing.JLabel lbl_addAdmin3;
    private javax.swing.JLabel lbl_addAdmin4;
    private javax.swing.JLabel lbl_addAdmin5;
    private javax.swing.JLabel lbl_addAdmin6;
    private javax.swing.JLabel lbl_addBus;
    private javax.swing.JLabel lbl_addDriver;
    private javax.swing.JLabel lbl_addEmployee;
    private javax.swing.JLabel lbl_addRoute;
    private javax.swing.JLabel lbl_addSchedule;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_exit4;
    private javax.swing.JLabel lbl_hompage;
    private javax.swing.JTable table_Display;
    private javax.swing.JTextField txt_dest;
    private javax.swing.JTextField txt_distance;
    private javax.swing.JTextField txt_duration;
    private javax.swing.JTextField txt_source;
    // End of variables declaration//GEN-END:variables
}
