/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JPanel;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asghar Qambar Rizvi
 */
public class AdminViewPass extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewPass
     */
    static String username;
    public AdminViewPass(String username) {
        initComponents();
        this.username=username;
        this.setExtendedState(MAXIMIZED_BOTH);
        viewAllPassengers();
        CustomHeaderRenderer renderer = new CustomHeaderRenderer();
        for (int i = 0; i < 5; i++) {
          tbl_display.getColumnModel().getColumn(i).setHeaderRenderer(renderer);
            }
    }
    class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
   private void viewAllPassengers() {
        DefaultTableModel model = new DefaultTableModel();

model.addColumn("Passenger ID");
model.addColumn("Name");
model.addColumn("Contact Number");
model.addColumn("Email");
model.addColumn("Gender");

String connectionString = "jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true";
String sql = "{call ViewPassenger()}"; // Call the stored procedure

try (Connection conn = DriverManager.getConnection(connectionString, "admin", "123456");
     CallableStatement stmt = conn.prepareCall(sql);
     ResultSet rs = stmt.executeQuery()) {

    while (rs.next()) {
        String passengerId = rs.getString("passengerId");
        String name = rs.getString("Name");
        String contactNumber = rs.getString("ContactNumber");
        String email = rs.getString("Email");
        String gender = rs.getString("Gender");

        model.addRow(new Object[]{passengerId, name, contactNumber, email, gender});
    }

    tbl_display.setModel(model);

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "An error occurred while retrieving passenger data", "Error", JOptionPane.ERROR_MESSAGE);
}

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_display = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new JpanelGradient();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl_exit4 = new javax.swing.JLabel();
        lbl_addBus = new javax.swing.JLabel();
        lbl_addDriver = new javax.swing.JLabel();
        lbl_addRoute = new javax.swing.JLabel();
        lbl_addEmployee = new javax.swing.JLabel();
        lbl_addSchedule = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_addAdmin2 = new javax.swing.JLabel();
        lbl_hompage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_addAdmin3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_addAdmin4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_addAdmin5 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbl_addAdmin6 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 204));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_display.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tbl_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_display.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_display.setFillsViewportHeight(true);
        tbl_display.setRowHeight(25);
        tbl_display.setSelectionBackground(new java.awt.Color(36, 136, 203));
        tbl_display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_display.setShowGrid(true);
        tbl_display.setShowVerticalLines(false);
        tbl_display.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 770, 450));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VIEW ALL PASSENGERS ");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 790, 78));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/bus.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/delivery.png"))); // NOI18N
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/division.png"))); // NOI18N
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/driver.png"))); // NOI18N
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/logout.png"))); // NOI18N
        jLabel38.setText("jLabel6");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/schedule.png"))); // NOI18N
        jLabel39.setText("jLabel7");
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_exit4.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_exit4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit4.setText("       E X I T");
        lbl_exit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exit4MouseExited(evt);
            }
        });

        lbl_addBus.setBackground(new Color(0,0,0,0 ));
        lbl_addBus.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addBus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addBus.setText("ADD A BUS");
        lbl_addBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addBusMouseExited(evt);
            }
        });

        lbl_addDriver.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addDriver.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addDriver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addDriver.setText("ADD A DRIVER");
        lbl_addDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addDriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addDriverMouseExited(evt);
            }
        });

        lbl_addRoute.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addRoute.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addRoute.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addRoute.setText("ADD A ROUTE");
        lbl_addRoute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addRouteMouseExited(evt);
            }
        });

        lbl_addEmployee.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addEmployee.setText("ADD EMPLOYEE");
        lbl_addEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addEmployeeMouseExited(evt);
            }
        });

        lbl_addSchedule.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addSchedule.setText("ADD SCHEDULE");
        lbl_addSchedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addScheduleMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/administrator.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin2.setText("ADD  ADMIN");
        lbl_addAdmin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin2MouseExited(evt);
            }
        });

        lbl_hompage.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_hompage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hompage.setText(" H O M E   P A G E");
        lbl_hompage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_hompage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_hompageMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/homepage.png"))); // NOI18N
        jLabel9.setText("jLabel7");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin3.setText("     VIEW PASSENGERS");
        lbl_addAdmin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin3MouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/passenger.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin4.setText("     RESERVATIONS");
        lbl_addAdmin4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin4MouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/reservation.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin5.setText("USER QUERIES");
        lbl_addAdmin5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin5MouseExited(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/query.png"))); // NOI18N
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addAdmin6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addAdmin6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addAdmin6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_addAdmin6.setText("FEEDBACKS");
        lbl_addAdmin6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addAdmin6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addAdmin6MouseExited(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/feedback.png"))); // NOI18N
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbl_hompage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_addAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_addAdmin6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addAdmin5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbl_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_hompage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_addAdmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbl_addAdmin4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addAdmin6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(lbl_addAdmin5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel38))
                    .addComponent(lbl_exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        lbl_bg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tbl_display.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void lbl_exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseClicked
        HOMEPAGE home=new HOMEPAGE();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_exit4MouseClicked

    private void lbl_exit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseEntered
        lbl_exit4.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseEntered

    private void lbl_exit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exit4MouseExited
        lbl_exit4.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exit4MouseExited

    private void lbl_addBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseClicked
        AdminAddBus addBus=new AdminAddBus(username);
        addBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addBusMouseClicked

    private void lbl_addBusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseEntered
        lbl_addBus.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addBusMouseEntered

    private void lbl_addBusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addBusMouseExited
        lbl_addBus.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addBusMouseExited

    private void lbl_addDriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseClicked
        AdminAddDriver addDriver=new AdminAddDriver(username);
        addDriver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addDriverMouseClicked

    private void lbl_addDriverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseEntered
        lbl_addDriver.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addDriverMouseEntered

    private void lbl_addDriverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addDriverMouseExited
        lbl_addDriver.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addDriverMouseExited

    private void lbl_addRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseClicked
        AdminAddRoute addRoute = new AdminAddRoute(username);
        addRoute.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addRouteMouseClicked

    private void lbl_addRouteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseEntered
        lbl_addRoute.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addRouteMouseEntered

    private void lbl_addRouteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addRouteMouseExited
        lbl_addRoute.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addRouteMouseExited

    private void lbl_addEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseClicked
        AdminAddEmploye addEmp=new AdminAddEmploye(username);
        addEmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addEmployeeMouseClicked

    private void lbl_addEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseEntered
        lbl_addEmployee.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addEmployeeMouseEntered

    private void lbl_addEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployeeMouseExited
        lbl_addEmployee.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addEmployeeMouseExited

    private void lbl_addScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseClicked
        AdminAddSch addSch = new AdminAddSch(username);
        addSch.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addScheduleMouseClicked

    private void lbl_addScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseEntered
        lbl_addSchedule.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addScheduleMouseEntered

    private void lbl_addScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addScheduleMouseExited
        lbl_addSchedule.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addScheduleMouseExited

    private void lbl_addAdmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseClicked
        AdminAddNew addAdmin = new AdminAddNew(username);
        addAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin2MouseClicked

    private void lbl_addAdmin2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseEntered
        lbl_addAdmin2.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin2MouseEntered

    private void lbl_addAdmin2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin2MouseExited
        lbl_addAdmin2.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin2MouseExited

    private void lbl_hompageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseClicked
        AdminHome home= new AdminHome(username);
        home.setVisible(true);
        this.setVisible(true);
    }//GEN-LAST:event_lbl_hompageMouseClicked

    private void lbl_hompageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseEntered
        lbl_hompage.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_hompageMouseEntered

    private void lbl_hompageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hompageMouseExited
        lbl_hompage.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_hompageMouseExited

    private void lbl_addAdmin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseClicked
        AdminViewPass pass=new AdminViewPass(username);
        pass.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin3MouseClicked

    private void lbl_addAdmin3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseEntered
        lbl_addAdmin3.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin3MouseEntered

    private void lbl_addAdmin3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin3MouseExited
        lbl_addAdmin3.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin3MouseExited

    private void lbl_addAdmin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseClicked
        AdminViewReser res = new AdminViewReser(username);
        res.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_addAdmin4MouseClicked

    private void lbl_addAdmin4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseEntered
        lbl_addAdmin4.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin4MouseEntered

    private void lbl_addAdmin4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin4MouseExited
        lbl_addAdmin4.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin4MouseExited

    private void lbl_addAdmin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseClicked
        AdminViewUserQueries query=new AdminViewUserQueries(username);
        query.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin5MouseClicked

    private void lbl_addAdmin5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseEntered
        lbl_addAdmin5.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin5MouseEntered

    private void lbl_addAdmin5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin5MouseExited
        lbl_addAdmin5.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin5MouseExited

    private void lbl_addAdmin6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseClicked
        AdminViewFeedback feed=new AdminViewFeedback(username);
        feed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addAdmin6MouseClicked

    private void lbl_addAdmin6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseEntered
        lbl_addAdmin6.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addAdmin6MouseEntered

    private void lbl_addAdmin6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addAdmin6MouseExited
        lbl_addAdmin6.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addAdmin6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewPass(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_addAdmin2;
    private javax.swing.JLabel lbl_addAdmin3;
    private javax.swing.JLabel lbl_addAdmin4;
    private javax.swing.JLabel lbl_addAdmin5;
    private javax.swing.JLabel lbl_addAdmin6;
    private javax.swing.JLabel lbl_addBus;
    private javax.swing.JLabel lbl_addDriver;
    private javax.swing.JLabel lbl_addEmployee;
    private javax.swing.JLabel lbl_addRoute;
    private javax.swing.JLabel lbl_addSchedule;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_exit4;
    private javax.swing.JLabel lbl_hompage;
    private javax.swing.JTable tbl_display;
    // End of variables declaration//GEN-END:variables
}
