/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asghar Qambar Rizvi
 */
public class ContactUs extends javax.swing.JFrame {

    /**
     * Creates new form ContactUs
     */
    private Border emptyBorder = BorderFactory.createEmptyBorder();
    public ContactUs() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JpanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        lbl_Signup = new javax.swing.JLabel();
        lbl_signin = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        lbl_about = new javax.swing.JLabel();
        lbl_heading1 = new javax.swing.JLabel();
        lbl_heading2 = new javax.swing.JLabel();
        lbl_heading3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_last = new javax.swing.JTextField();
        txt_first = new javax.swing.JTextField();
        txt_gmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_comments = new javax.swing.JTextArea();
        btn_submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUS BOOKING");

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SYSTEM");

        lbl_home.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_home.setForeground(new java.awt.Color(255, 255, 255));
        lbl_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_home.setText("HOME ");
        lbl_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_homeMouseExited(evt);
            }
        });

        lbl_Signup.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_Signup.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Signup.setText("SIGN UP");
        lbl_Signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_SignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_SignupMouseExited(evt);
            }
        });

        lbl_signin.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_signin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_signin.setText("SIGN IN");
        lbl_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_signinMouseExited(evt);
            }
        });

        lbl_contact.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_contact.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_contact.setText("CONTACT US");
        lbl_contact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_contactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_contactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_contactMouseExited(evt);
            }
        });

        lbl_about.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_about.setForeground(new java.awt.Color(255, 255, 255));
        lbl_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_about.setText("ABOUT US");
        lbl_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseExited(evt);
            }
        });

        lbl_heading1.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lbl_heading1.setText("CONTACT US");
        lbl_heading1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_heading2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbl_heading2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heading2.setText("or need assistance, our team is here to help.");
        lbl_heading2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_heading3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbl_heading3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_heading3.setText("We'd love to hear from you! Whether you have questions, feedback,");
        lbl_heading3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("What can we help you with ?");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("First Name :");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Last Name :");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Email :");

        txt_last.setBackground(new Color(0,0,0,0));
        txt_last.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        txt_last.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_last.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lastKeyTyped(evt);
            }
        });

        txt_first.setBackground(new Color(0,0,0,0));
        txt_first.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        txt_first.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_first.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstKeyTyped(evt);
            }
        });

        txt_gmail.setBackground(new Color(0,0,0,0));
        txt_gmail.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        txt_gmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_gmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_gmailFocusLost(evt);
            }
        });
        txt_gmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gmailActionPerformed(evt);
            }
        });
        txt_gmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_gmailKeyTyped(evt);
            }
        });

        txt_comments.setColumns(20);
        txt_comments.setFont(new java.awt.Font("SimSun", 0, 24)); // NOI18N
        txt_comments.setRows(5);
        jScrollPane1.setViewportView(txt_comments);

        btn_submit.setBackground(new java.awt.Color(0, 204, 204));
        btn_submit.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        btn_submit.setText("S U B M I T");
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_submitMouseExited(evt);
            }
        });
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_last, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 52, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_first, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_last, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1210, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_home, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lbl_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(lbl_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lbl_about, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(155, 155, 155))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_heading2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_heading3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_about, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_contact)
                        .addComponent(lbl_signin)
                        .addComponent(lbl_home)
                        .addComponent(lbl_Signup))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lbl_heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lbl_heading3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_heading2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        HOMEPAGE1 home = new HOMEPAGE1();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void lbl_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseEntered
        lbl_home.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_home.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_homeMouseEntered

    private void lbl_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseExited
        lbl_home.setForeground(new Color(255,255,255));
        lbl_home.setBorder(emptyBorder);
    }//GEN-LAST:event_lbl_homeMouseExited

    private void lbl_SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SignupMouseClicked
        PassengerSignUP signup=new PassengerSignUP();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_SignupMouseClicked

    private void lbl_SignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SignupMouseEntered
        lbl_Signup.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_Signup.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_SignupMouseEntered

    private void lbl_SignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SignupMouseExited
        lbl_Signup.setForeground(new Color(255,255,255));
        lbl_Signup.setBorder(emptyBorder);
    }//GEN-LAST:event_lbl_SignupMouseExited

    private void lbl_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseClicked
        PassengerLogin login=new PassengerLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_signinMouseClicked

    private void lbl_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseEntered
        lbl_signin.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_signin.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_signinMouseEntered

    private void lbl_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseExited
        lbl_signin.setForeground(new Color(255,255,255));
        lbl_signin.setBorder(emptyBorder);
    }//GEN-LAST:event_lbl_signinMouseExited

    private void lbl_contactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_contactMouseEntered
        lbl_contact.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_contact.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_contactMouseEntered

    private void lbl_contactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_contactMouseExited
        lbl_contact.setForeground(new Color(255,255,255));
        lbl_contact.setBorder(emptyBorder);
    }//GEN-LAST:event_lbl_contactMouseExited

    private void lbl_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseEntered
        lbl_about.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_about.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_aboutMouseEntered

    private void lbl_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseExited
        lbl_about.setForeground(new Color(255,255,255));
        lbl_about.setBorder(emptyBorder );
    }//GEN-LAST:event_lbl_aboutMouseExited

    private void txt_gmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gmailActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
                String first = txt_first.getText().trim();
                String last = txt_last.getText().trim();
                String email = txt_gmail.getText().trim();
                String comm = txt_comments.getText().trim();

                if (first.isEmpty() || last.isEmpty() || email.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ContactUs.class.getName()).log(Level.SEVERE, null, ex);
        }
                // Call the stored procedure to insert values into ContactUs table
                try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                     CallableStatement stmt = conn.prepareCall("{call InsertIntoContactus(?, ?, ?, ?)}")) {

                    stmt.setString(1, first);
                    stmt.setString(2, last);
                    stmt.setString(3, email);
                    stmt.setString(4, comm);

                    stmt.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Record inserted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    // Clear the text fields after successful insertion
                    txt_first.setText("");
                    txt_last.setText("");
                    txt_gmail.setText("");
                    txt_comments.setText("");

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error inserting record: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            
        
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_firstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstKeyTyped
    String name = txt_first.getText();
    char keyChar = evt.getKeyChar();

    // Check if a key was pressed and it's not a backspace, delete, or space key
    if (keyChar != KeyEvent.VK_BACK_SPACE && keyChar != KeyEvent.VK_DELETE && keyChar != KeyEvent.VK_SPACE) {
        // Check if the entered character is not an alphabet
        if (!Character.isAlphabetic(keyChar)) {
            // Consume the event to prevent the character from being added
            evt.consume();
            // Show an error message to the user
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter only alphabetic characters.");
            return;
        }  }      // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstKeyTyped

    private void txt_lastKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastKeyTyped
        String name = txt_last.getText();
    char keyChar = evt.getKeyChar();

    // Check if a key was pressed and it's not a backspace, delete, or space key
    if (keyChar != KeyEvent.VK_BACK_SPACE && keyChar != KeyEvent.VK_DELETE && keyChar != KeyEvent.VK_SPACE) {
        // Check if the entered character is not an alphabet
        if (!Character.isAlphabetic(keyChar)) {
            // Consume the event to prevent the character from being added
            evt.consume();
            // Show an error message to the user
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter only alphabetic characters.");
            return;
        }}
    }//GEN-LAST:event_txt_lastKeyTyped

    private void txt_gmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_gmailKeyTyped
         String email = txt_gmail.getText();
    
        // Check if the length of the current text is equal to or greater than 31
        if (email.length() >= 31) {
            // Consume the event to prevent the character from being added
            evt.consume();
            // Show an error message to the user
            javax.swing.JOptionPane.showMessageDialog(null, "Email length cannot exceed 30 characters.");
            return;
        }
    }//GEN-LAST:event_txt_gmailKeyTyped

    private void txt_gmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_gmailFocusLost
        String email = txt_gmail.getText();

    // Check if the email meets the criteria
    if (email.length() >= 31 || !email.contains("@") || !email.endsWith(".com")) {
        // Show an error message to the user
        javax.swing.JOptionPane.showMessageDialog(null, "Email must be less than 31 characters, contain '@', and end with '.com'.");
        txt_gmail.requestFocus();
    } 
    }//GEN-LAST:event_txt_gmailFocusLost

    private void btn_submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseEntered
        btn_submit.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_submitMouseEntered

    private void btn_submitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_submitMouseExited
       btn_submit.setForeground(new Color(0,0,0));

    }//GEN-LAST:event_btn_submitMouseExited

    private void lbl_contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_contactMouseClicked
        ContactUs con = new ContactUs();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_contactMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Signup;
    private javax.swing.JLabel lbl_about;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_heading1;
    private javax.swing.JLabel lbl_heading2;
    private javax.swing.JLabel lbl_heading3;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_signin;
    private javax.swing.JTextArea txt_comments;
    private javax.swing.JTextField txt_first;
    private javax.swing.JTextField txt_gmail;
    private javax.swing.JTextField txt_last;
    // End of variables declaration//GEN-END:variables
}
