/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Asghar Qambar Rizvi
 */
public class PassengerLogin extends javax.swing.JFrame {

    /**
     * Creates new form PassengerLogin
     */
    private Border emptyBorder = BorderFactory.createEmptyBorder();
    public PassengerLogin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
 
    }
    
    class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JpanelGradient();
        pnl_bg = new javax.swing.JPanel();
        txt_gmail = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_about = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        lbl_signin = new javax.swing.JLabel();
        lbl_Signup = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_bg.setBackground(new java.awt.Color(255, 255, 255));
        pnl_bg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_bg.setForeground(new java.awt.Color(255, 255, 255));
        pnl_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_gmail.setBackground(new Color(0,0,0,0));
        txt_gmail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_gmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        pnl_bg.add(txt_gmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 420, 33));

        btn_login.setBackground(new java.awt.Color(0, 102, 102));
        btn_login.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("L O G I N ");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pnl_bg.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 430, 45));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("P A S S W O R D :");
        pnl_bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 217, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("U S E R   N A M E:");
        pnl_bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 360, -1));

        txt_pass.setBackground(new Color(0,0,0,0));
        txt_pass.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        pnl_bg.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 420, 40));

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("DON'T HAVE AN ACCOUNT?    SIGNUP");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        pnl_bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 570, 20));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("W E L C O M E   B A C K ");
        pnl_bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 100));

        lbl_about.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_about.setForeground(new java.awt.Color(255, 255, 255));
        lbl_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_about.setText("ABOUT US");
        lbl_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_aboutMouseExited(evt);
            }
        });

        lbl_contact.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_contact.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_contact.setText("CONTACT US");
        lbl_contact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_contactMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_contactMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_contactMouseExited(evt);
            }
        });

        lbl_signin.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_signin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_signin.setText("SIGN IN");
        lbl_signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_signinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_signinMouseExited(evt);
            }
        });

        lbl_Signup.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_Signup.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Signup.setText("SIGN UP");
        lbl_Signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_SignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_SignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_SignupMouseExited(evt);
            }
        });

        lbl_home.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        lbl_home.setForeground(new java.awt.Color(255, 255, 255));
        lbl_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_home.setText("HOME ");
        lbl_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_homeMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SYSTEM");

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BUS BOOKING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219)
                                .addComponent(lbl_home, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lbl_Signup, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(lbl_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lbl_about, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(498, 498, 498)
                        .addComponent(pnl_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_about, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_contact)
                            .addComponent(lbl_signin)
                            .addComponent(lbl_home)
                            .addComponent(lbl_Signup))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(pnl_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        if (txt_gmail.getText().isEmpty() || txt_pass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "F I E L D S   A R E   E M P T Y ! ! !");
        }
        else{
            String id=txt_gmail.getText();
            String pass=txt_pass.getText();
            String sqlQuery= "SELECT *FROM passenger where passengerid= '"+id+"' and password ='"+pass+"'";
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn= DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true","admin","123456");
                PreparedStatement pst=conn.prepareStatement(sqlQuery);
                ResultSet rs=pst.executeQuery();
                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "W R O N G  I D   O R   P A S S W O R D");
                    
                }
                else
                {
                    PassBookBus pass1=new PassBookBus(id);
                    pass1.setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    
    
    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_loginMouseClicked

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        btn_login.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        btn_login.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btn_loginMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        PassengerSignUP login=new PassengerSignUP();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setForeground(new Color(0,204,204));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jLabel9MouseExited

    private void lbl_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseEntered
        lbl_about.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
    }//GEN-LAST:event_lbl_aboutMouseEntered

    private void lbl_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_aboutMouseExited
        lbl_about.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_aboutMouseExited

    private void lbl_contactMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_contactMouseEntered
        lbl_contact.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_contact.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_contactMouseEntered

    private void lbl_contactMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_contactMouseExited
        lbl_contact.setForeground(new Color(255,255,255));
        lbl_contact.setBorder(emptyBorder);
    }//GEN-LAST:event_lbl_contactMouseExited

    private void lbl_signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseClicked
        PassengerLogin login=new PassengerLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_signinMouseClicked

    private void lbl_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseEntered
        lbl_signin.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_signin.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_signinMouseEntered

    private void lbl_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_signinMouseExited
        lbl_signin.setForeground(new Color(255,255,255));
        lbl_signin.setBorder(emptyBorder);
    }//GEN-LAST:event_lbl_signinMouseExited

    private void lbl_SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SignupMouseClicked
        PassengerSignUP signup=new PassengerSignUP();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_SignupMouseClicked

    private void lbl_SignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SignupMouseEntered
        lbl_Signup.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_Signup.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_SignupMouseEntered

    private void lbl_SignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_SignupMouseExited
        lbl_Signup.setForeground(new Color(255,255,255));
        lbl_Signup.setBorder(emptyBorder);
    }//GEN-LAST:event_lbl_SignupMouseExited

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        HOMEPAGE1 home = new HOMEPAGE1();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_homeMouseClicked

    private void lbl_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseEntered
        lbl_home.setForeground(new Color(0,0,0));
        Border initialBorder = new MatteBorder(0, 0, 3, 0, Color.BLACK); // 1-pixel matte border
        lbl_home.setBorder(initialBorder);
    }//GEN-LAST:event_lbl_homeMouseEntered

    private void lbl_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseExited
        lbl_home.setForeground(new Color(255,255,255));
        lbl_home.setBorder(emptyBorder);
    }//GEN-LAST:event_lbl_homeMouseExited

    private void lbl_contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_contactMouseClicked
ContactUs con = new ContactUs();
        con.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_contactMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Signup;
    private javax.swing.JLabel lbl_about;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_signin;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JTextField txt_gmail;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
    
    
}

