/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Asghar Qambar Rizvi
 */
public class PassTicket extends javax.swing.JFrame {

    /**
     * Creates new form PassTicket
     */
    String departureTimeFromDB;
    static String id;
    public PassTicket(String id) {
        initComponents();
        this.id=id;
        setExtendedState(MAXIMIZED_BOTH);
        displayReservations();
        CustomHeaderRenderer renderer = new CustomHeaderRenderer();
        for (int i = 0; i < 5; i++) {
          table_display.getColumnModel().getColumn(i).setHeaderRenderer(renderer);
            }
    }
    class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
   private void displayReservations() {
    try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456")) {
            CallableStatement cstmt = conn.prepareCall("{call DisplayReservations(?)}");
            cstmt.setString(1, id); // Set the passenger ID parameter

            ResultSet rs = cstmt.executeQuery();

            // Create a table model and set the column names
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Source");
            model.addColumn("Destination");
            model.addColumn("Departure Time");
            model.addColumn("Seat Number");
            model.addColumn("Fare");

            // Populate the table model with data from the result set
            while (rs.next()) {
                Object[] row = new Object[6];
                row[0] = rs.getString("Source");
                row[1] = rs.getString("Destination");
                row[2] = rs.getString("Departure_time");
                row[3] = rs.getString("Seat_number");
                row[4] = rs.getDouble("Fare");

                model.addRow(row);
            }

            // Set the table model to the JTable
            table_display.setModel(model);
        }
    } catch (Exception e) {
        e.printStackTrace(); // Handle exceptions appropriately
        JOptionPane.showMessageDialog(this, "An error occurred while retrieving data", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JpanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_BookBus = new javax.swing.JLabel();
        lbl_payment = new javax.swing.JLabel();
        lbl_ticket = new javax.swing.JLabel();
        lbl_profle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_addEmployee1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_display = new javax.swing.JTable();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/bus.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/ticket.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/profile.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/credit-card.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/logout.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_exit.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setText("       E X I T");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
        });

        lbl_BookBus.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_BookBus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BookBus.setText("BOOK A TICKET");
        lbl_BookBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_BookBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseExited(evt);
            }
        });

        lbl_payment.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_payment.setForeground(new java.awt.Color(255, 255, 255));
        lbl_payment.setText("P A Y M E N T");
        lbl_payment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseExited(evt);
            }
        });

        lbl_ticket.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_ticket.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ticket.setText("R E S E R V A T I O N S");
        lbl_ticket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseExited(evt);
            }
        });

        lbl_profle.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_profle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_profle.setText("P R O F I L E");
        lbl_profle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_profle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_profleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_profleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_profleMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/feedback.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addEmployee1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addEmployee1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addEmployee1.setText("F E E D  B A C K");
        lbl_addEmployee1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_addEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ticket, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_profle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_BookBus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_profle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_BookBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lbl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 830));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("V I E W   Y O U R   R E S E R V A T I O N S");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 1110, 80));

        table_display.setBorder(new javax.swing.border.MatteBorder(null));
        table_display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_display.setFillsViewportHeight(true);
        table_display.setRowHeight(25);
        table_display.setSelectionBackground(new java.awt.Color(36, 136, 203));
        table_display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_display.setShowGrid(true);
        table_display.setShowVerticalLines(false);
        table_display.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 880, -1));

        lbl_bg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 1940, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        HOMEPAGE home=new HOMEPAGE();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_BookBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseClicked
        PassBookBus bookBus=new PassBookBus(id);
        bookBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_BookBusMouseClicked

    private void lbl_BookBusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseEntered

        lbl_BookBus.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_BookBusMouseEntered

    private void lbl_BookBusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseExited
        lbl_BookBus.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_BookBusMouseExited

    private void lbl_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseClicked
        PassPayment payment= new PassPayment(id);
        payment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_paymentMouseClicked

    private void lbl_paymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseEntered
        lbl_payment.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_paymentMouseEntered

    private void lbl_paymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseExited
        lbl_payment.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_paymentMouseExited

    private void lbl_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseClicked
        PassTicket ticket=new PassTicket(id);
        ticket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_ticketMouseClicked

    private void lbl_ticketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseEntered
        lbl_ticket.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ticketMouseEntered

    private void lbl_ticketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseExited
        lbl_ticket.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ticketMouseExited

    private void lbl_profleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseClicked
        PassProfile pro=new PassProfile(id);
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_profleMouseClicked

    private void lbl_profleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseEntered
        lbl_profle.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_profleMouseEntered

    private void lbl_profleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseExited
        lbl_profle.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_profleMouseExited

    private void lbl_addEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseClicked
        PassFeedBack feed=new PassFeedBack(id);
        feed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addEmployee1MouseClicked

    private void lbl_addEmployee1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseEntered
        lbl_addEmployee1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addEmployee1MouseEntered

    private void lbl_addEmployee1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseExited
        lbl_addEmployee1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addEmployee1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassTicket(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_BookBus;
    private javax.swing.JLabel lbl_addEmployee1;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_payment;
    private javax.swing.JLabel lbl_profle;
    private javax.swing.JLabel lbl_ticket;
    private javax.swing.JTable table_display;
    // End of variables declaration//GEN-END:variables
}
