/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

/**
 *
 * @author Asghar Qambar Rizvi
 */
public class PassBookBus extends javax.swing.JFrame {

    /**
     * Creates new form PassBookBus
     */
    static String id;
    public PassBookBus(String id) {
        initComponents();
        displaSourceAndDestination();
        this.id=id;
        setExtendedState(MAXIMIZED_BOTH);
        CustomHeaderRenderer renderer = new CustomHeaderRenderer();
        for (int i = 0; i < 8; i++) {
          tbl_display.getColumnModel().getColumn(i).setHeaderRenderer(renderer);
            }
    }
    class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    private void displaSourceAndDestination(){
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn= DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=Mydatabase;encrypt=true;trustServerCertificate=true","admin","123456");
            CallableStatement cs = conn.prepareCall("{call DisplayAllSources}");
            ResultSet rs = cs.executeQuery();

    // Populate combo box with results
    while (rs.next()) {
        String source = rs.getString("Source");
        cmb_source.addItem(source);
    }   
    cs = conn.prepareCall("{call DisplayAllDestination}");
    rs = cs.executeQuery();
    while (rs.next()) {
        String source = rs.getString("destination");
        cmb_dest.addItem(source);
    } 
    
    
    // Close resources
    rs.close();
    cs.close();
    conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JpanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_BookBus = new javax.swing.JLabel();
        lbl_payment = new javax.swing.JLabel();
        lbl_ticket = new javax.swing.JLabel();
        lbl_profle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_addEmployee1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new JpanelGradient();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmb_source = new javax.swing.JComboBox<>();
        cmb_dest = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_display = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txt_schID = new javax.swing.JTextField();
        btn_Sche = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        comboBoxSeats = new javax.swing.JComboBox<>();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/bus.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/ticket.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/profile.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/credit-card.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/logout.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_exit.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setText("       E X I T");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
        });

        lbl_BookBus.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_BookBus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BookBus.setText("BOOK A TICKET");
        lbl_BookBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_BookBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseExited(evt);
            }
        });

        lbl_payment.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_payment.setForeground(new java.awt.Color(255, 255, 255));
        lbl_payment.setText("P A Y M E N T");
        lbl_payment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseExited(evt);
            }
        });

        lbl_ticket.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_ticket.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ticket.setText("R E S E R V A T I O N S");
        lbl_ticket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseExited(evt);
            }
        });

        lbl_profle.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_profle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_profle.setText("P R O F I L E");
        lbl_profle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_profle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_profleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_profleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_profleMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/feedback.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addEmployee1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addEmployee1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addEmployee1.setText("F E E D  B A C K");
        lbl_addEmployee1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_addEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ticket, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_profle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_BookBus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_profle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_BookBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lbl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 830));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("        B O O K    Y O U R   T I C K E T ! ! !       ");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 720, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH SCHEDULE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("S E L E C T   T H E   D E S T I N A T I O N :");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("S E L E C T   T H E   S O U R C E  :");

        cmb_source.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[-S E L E C T-]" }));

        cmb_dest.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_dest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[-S E L E C T-]" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_source, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_source, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(cmb_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 560, 320));

        tbl_display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbl_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SCHEDULE ID", "ROUTE ID", "BUS ID", "SOURCE", "DESTINATION", "DEPARTURE TIME", "ARRIVAL TIME", "FARE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_display.setRowHeight(25);
        tbl_display.setSelectionBackground(new java.awt.Color(36, 136, 203));
        tbl_display.setShowGrid(true);
        tbl_display.setShowVerticalLines(false);
        tbl_display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_displayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 870, 130));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel16.setText("T Y P E  T H E  S C H E D U L E  I D :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, -1, 40));

        txt_schID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_schID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_schID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_schID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_schIDActionPerformed(evt);
            }
        });
        getContentPane().add(txt_schID, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 130, 40));

        btn_Sche.setBackground(new java.awt.Color(0, 153, 153));
        btn_Sche.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Sche.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sche.setText("BOOK THIS SCHEDULE");
        btn_Sche.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Sche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ScheActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sche, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 690, 260, 40));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel17.setText("S E A T   N U M B E R :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 640, -1, 40));

        comboBoxSeats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboBoxSeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[-SEAT NUMBER-]" }));
        comboBoxSeats.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(comboBoxSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 640, 200, 30));

        lbl_bg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 1940, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   private void displayTable() {
    DefaultTableModel tableModel = (DefaultTableModel) tbl_display.getModel();
    String source = (String) cmb_source.getSelectedItem();
    String destination = (String) cmb_dest.getSelectedItem();
    tableModel.setRowCount(0);

    try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection conn= DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=Mydatabase;encrypt=true;trustServerCertificate=true","admin","123456");
        CallableStatement cstmt = conn.prepareCall("{call GetScheduleBySourceAndDestination(?,?)}");
          cstmt.setString(1, source); // Set the parameter value
           cstmt.setString(2, destination);
          ResultSet rs = cstmt.executeQuery();
          boolean hasData = false; // Flag to track if data is present
        while (rs.next()) {
            hasData = true; // Set flag to true if data is found
            Object[] row = new Object[8];
            for (int i = 0; i < 8; i++) {
                row[i] = rs.getObject(i + 1);
            }
            tableModel.addRow(row);
        }
         if (!hasData) {
            JOptionPane.showMessageDialog(this, "NO SCHEDULE FOUND FOR THIS SOURCE AND DESTINATION");
        }
        // Close resources
        rs.close();
        cstmt.close();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private ArrayList<Integer> getBookedSeats(String busId) {
    ArrayList<Integer> bookedSeats = new ArrayList<>();

    try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=Mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
         CallableStatement stmt = conn.prepareCall("{call ShowBusSeatNumberByBusid(?)}")) {

        stmt.setString(1, busId);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            bookedSeats.add(rs.getInt("Seat_number"));
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error fetching booked seats: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    return bookedSeats;
}
    private void populateAvailableSeats(String busId) {
        ArrayList<Integer> allSeats = new ArrayList<>();
        for (int i = 1; i <= 50; i++) {
            allSeats.add(i);
        }

        ArrayList<Integer> bookedSeats = getBookedSeats(busId);
        allSeats.removeAll(bookedSeats);

        for (Integer seat : allSeats) {
            String s = seat.toString();
            comboBoxSeats.addItem(s);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cmb_source.getSelectedIndex()==0 && cmb_dest.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this, "EMPTY FIELD");
        }
        else{
            displayTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_schIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_schIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_schIDActionPerformed

    private void btn_ScheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ScheActionPerformed
       
        if (comboBoxSeats.getSelectedIndex()==0 ) {
            JOptionPane.showMessageDialog(this, " FIELD IS EMPTY");
        }
        else{
             int row = tbl_display.getSelectedRow();
              String schID = tbl_display.getValueAt(row, 0).toString();
       
           // String schID = txt_schID.getText();
            String seatNo= (String) comboBoxSeats.getSelectedItem();
            String status= "Pending";
            String sql = "Insert into reservation (Passengerid,Scheduleid,Seat_number,Status) values(?,?,?,?)";
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                PreparedStatement insertStmt = conn.prepareStatement(sql);
                insertStmt.setString(1, id);
                insertStmt.setString(2, schID);
                insertStmt.setString(3, seatNo);
                insertStmt.setString(4,status);
                int rowsInserted = insertStmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "You have been Reserved successfully!");
                txt_schID.setText("");
                comboBoxSeats.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "Registration failed.");
            }
            insertStmt.close();
            } catch (Exception e) {
            }
        }
        
    }//GEN-LAST:event_btn_ScheActionPerformed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        HOMEPAGE home=new HOMEPAGE();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_BookBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseClicked
        PassBookBus bookBus=new PassBookBus(id);
        bookBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_BookBusMouseClicked

    private void lbl_BookBusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseEntered

        lbl_BookBus.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_BookBusMouseEntered

    private void lbl_BookBusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseExited
        lbl_BookBus.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_BookBusMouseExited

    private void lbl_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseClicked
        PassPayment payment= new PassPayment(id);
        payment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_paymentMouseClicked

    private void lbl_paymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseEntered
        lbl_payment.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_paymentMouseEntered

    private void lbl_paymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseExited
        lbl_payment.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_paymentMouseExited

    private void lbl_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseClicked
        PassTicket ticket=new PassTicket(id);
        ticket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_ticketMouseClicked

    private void lbl_ticketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseEntered
        lbl_ticket.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ticketMouseEntered

    private void lbl_ticketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseExited
        lbl_ticket.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ticketMouseExited

    private void lbl_profleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseClicked
        PassProfile pro=new PassProfile(id);
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_profleMouseClicked

    private void lbl_profleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseEntered
        lbl_profle.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_profleMouseEntered

    private void lbl_profleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseExited
        lbl_profle.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_profleMouseExited

    private void lbl_addEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseClicked
        PassFeedBack feed=new PassFeedBack(id);
        feed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addEmployee1MouseClicked

    private void lbl_addEmployee1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseEntered
        lbl_addEmployee1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addEmployee1MouseEntered

    private void lbl_addEmployee1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseExited
        lbl_addEmployee1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addEmployee1MouseExited

    private void tbl_displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_displayMouseClicked
       int row = tbl_display.getSelectedRow();
        if (row != -1) {
            // Assuming busid is in the 3rd column (index 2) of the table
            String busid = tbl_display.getValueAt(row, 2).toString();
            populateAvailableSeats(busid);
        }
        else{}
    }//GEN-LAST:event_tbl_displayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassBookBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassBookBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassBookBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassBookBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassBookBus(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sche;
    private javax.swing.JComboBox<String> cmb_dest;
    private javax.swing.JComboBox<String> cmb_source;
    private javax.swing.JComboBox<String> comboBoxSeats;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_BookBus;
    private javax.swing.JLabel lbl_addEmployee1;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_payment;
    private javax.swing.JLabel lbl_profle;
    private javax.swing.JLabel lbl_ticket;
    private javax.swing.JTable tbl_display;
    private javax.swing.JTextField txt_schID;
    // End of variables declaration//GEN-END:variables
}
