/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;

import static busticketmanagement.PassTicket.id;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Asghar Qambar Rizvi
 */
public class PassFeedBack extends javax.swing.JFrame {

    /**
     * Creates new form PassFeedBack
     */
    static String id;
    String schID=" ";
    public PassFeedBack(String id) {
        initComponents();
        this.id=id;
        displayInfo();
        setExtendedState(MAXIMIZED_BOTH);
    }
     class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
     private void displayInfo(){
     try {
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");

    // Step 1: Find the schedule ID for the given passenger ID
    String schID = null;
    CallableStatement cstmt = conn.prepareCall("{call FindScheduleID(?)}");
    cstmt.setString(1, id); // Set parameter value
    ResultSet rs = cstmt.executeQuery();

    if (rs.next()) {
        // Retrieve the scheduleId value
        schID = rs.getString("ScheduleId");
    } else {
        // No schedule found for the passenger
        JOptionPane.showMessageDialog(this, "FIRST BOOK A TICKET AND TRAVEL", "Error", JOptionPane.ERROR_MESSAGE);
        PassBookBus bus = new PassBookBus(id);
        bus.setVisible(true);
        this.dispose();
        return; // Exit the method
    }

    // Step 2: Display information for feedback
    CallableStatement cstmt1 = conn.prepareCall("{call DisplayInfoForFeedback(?, ?)}");
    cstmt1.setString(1, id); // Set passenger ID
    cstmt1.setInt(2, Integer.parseInt(schID)); // Set schedule ID

    rs = cstmt1.executeQuery();

    // Check if the result set has any data
    if (rs.next()) {
        // Retrieve data from the result set
        String name = rs.getString("Name");
        String email = rs.getString("Email");
        String source = rs.getString("Source");
        String destination = rs.getString("Destination");
        String seatNumber = rs.getString("Seat_number");
        double fare = rs.getDouble("Fare");

        // Set the data to the text fields
        txt_name.setText(name);
        txt_email.setText(email);
        txt_source.setText(source);
        txt_dest.setText(destination);
        txt_seatNo.setText(seatNumber);
        txt_fare.setText(String.valueOf(fare));
    } else {
        // No data found for the passenger
        JOptionPane.showMessageDialog(this, "FIRST BOOK A TICKET AND TRAVEL", "Error", JOptionPane.ERROR_MESSAGE);
        btn_submit.setVisible(false);
        
    }

    // Close resources
    rs.close();
    cstmt.close();
    cstmt1.close();
    conn.close();
} catch (Exception ex) {
    ex.printStackTrace();
    // Handle SQL exception
    JOptionPane.showMessageDialog(this, "An error occurred while retrieving data", "Error", JOptionPane.ERROR_MESSAGE);
}

     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JpanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_BookBus = new javax.swing.JLabel();
        lbl_payment = new javax.swing.JLabel();
        lbl_ticket = new javax.swing.JLabel();
        lbl_profle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_addEmployee1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new JpanelGradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_source = new javax.swing.JTextField();
        txt_dest = new javax.swing.JTextField();
        txt_fare = new javax.swing.JTextField();
        txt_seatNo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmb_rating = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_comm = new javax.swing.JTextArea();
        btn_submit = new javax.swing.JButton();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/bus.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/ticket.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/profile.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/credit-card.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/logout.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_exit.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setText("       E X I T");
        lbl_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
        });

        lbl_BookBus.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_BookBus.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BookBus.setText("BOOK A TICKET");
        lbl_BookBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_BookBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_BookBusMouseExited(evt);
            }
        });

        lbl_payment.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_payment.setForeground(new java.awt.Color(255, 255, 255));
        lbl_payment.setText("P A Y M E N T");
        lbl_payment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_paymentMouseExited(evt);
            }
        });

        lbl_ticket.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_ticket.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ticket.setText("R E S E R V A T I O N S");
        lbl_ticket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ticketMouseExited(evt);
            }
        });

        lbl_profle.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_profle.setForeground(new java.awt.Color(255, 255, 255));
        lbl_profle.setText("P R O F I L E");
        lbl_profle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_profle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_profleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_profleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_profleMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busticketmanagement/icons/feedback.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lbl_addEmployee1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbl_addEmployee1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addEmployee1.setText("F E E D  B A C K");
        lbl_addEmployee1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_addEmployee1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addEmployee1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_addEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ticket, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_profle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_BookBus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_profle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_BookBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lbl_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_addEmployee1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addComponent(lbl_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 830));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("                         GIVE FEEDBACK OF YOUR RIDE");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 51, 51)));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 1110, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("NAME:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("EMAIL:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("SOURCE:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("DESTINATION:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("FARE:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("SEAT NUMBER: ");

        txt_name.setEditable(false);
        txt_name.setBackground(new Color(0,0,0,0));
        txt_name.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_email.setEditable(false);
        txt_email.setBackground(new Color(0,0,0,0));
        txt_email.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        txt_source.setEditable(false);
        txt_source.setBackground(new Color(0,0,0,0));
        txt_source.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txt_source.setForeground(new java.awt.Color(255, 255, 255));
        txt_source.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_source.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sourceActionPerformed(evt);
            }
        });

        txt_dest.setEditable(false);
        txt_dest.setBackground(new Color(0,0,0,0));
        txt_dest.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txt_dest.setForeground(new java.awt.Color(255, 255, 255));
        txt_dest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_dest.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_destActionPerformed(evt);
            }
        });

        txt_fare.setEditable(false);
        txt_fare.setBackground(new Color(0,0,0,0));
        txt_fare.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txt_fare.setForeground(new java.awt.Color(255, 255, 255));
        txt_fare.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fare.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        txt_seatNo.setEditable(false);
        txt_seatNo.setBackground(new Color(0,0,0,0));
        txt_seatNo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txt_seatNo.setForeground(new java.awt.Color(255, 255, 255));
        txt_seatNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_seatNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_seatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_seatNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_source, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(txt_dest)
                    .addComponent(txt_seatNo))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_source, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txt_dest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txt_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_seatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 1070, 310));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel14.setText("S E L E C T   R A T I  N G (/5) : ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 250, 40));

        cmb_rating.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        cmb_rating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[ - SELECT- ]", "1", "2", "3", "4", "5", " " }));
        getContentPane().add(cmb_rating, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 160, 40));

        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setText("C O M M E N T S : ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 250, 30));

        txt_comm.setBackground(new java.awt.Color(36, 136, 203));
        txt_comm.setColumns(20);
        txt_comm.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_comm.setForeground(new java.awt.Color(255, 255, 255));
        txt_comm.setRows(5);
        jScrollPane1.setViewportView(txt_comm);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 420, 210));

        btn_submit.setBackground(new java.awt.Color(0, 204, 204));
        btn_submit.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("S U B M I T   F E E D B A C K ");
        btn_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 740, 300, 50));

        lbl_bg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setOpaque(true);
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 1940, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sourceActionPerformed

    private void txt_destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_destActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_destActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_seatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_seatNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_seatNoActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        if (cmb_rating.getSelectedIndex()==0 || txt_comm.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "FIELDS ARE EMPTY");
        }
        else{
            int rating = Integer.parseInt(cmb_rating.getSelectedItem().toString());
            String comments=txt_comm.getText();
            
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
        
                CallableStatement cstmt = conn.prepareCall("{call FindScheduleID(?)}");
                cstmt.setString(1, id); // Set parameter value
                ResultSet rs = cstmt.executeQuery();

                if (rs.next()) {
                    // Retrieve the scheduleId value
                    schID = rs.getString("ScheduleId");
                    
                }
                int schIDint= Integer.parseInt(schID);
                 try {
                    cstmt = conn.prepareCall("{call InserIntoFeedback(?, ?, ?, ?)}");
                    cstmt.setString(1, id); // Set passengerId parameter
                    cstmt.setInt(2, schIDint);      // Set ScheduleID parameter
                    cstmt.setInt(3, rating);          // Set rating parameter
                    cstmt.setString(4, comments);     // Set comments parameter
                    cstmt.executeUpdate();

        // Close resources
        cstmt.close();
        conn.close();
        
        JOptionPane.showMessageDialog(this, "Feedback submitted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        cmb_rating.setSelectedIndex(0);
        txt_comm.setText("");
        PassProfile profile = new PassProfile(id);
        profile.setVisible(true);
        this.dispose();
    } catch (Exception ex) {
        ex.printStackTrace();
        // Handle SQL exception
        JOptionPane.showMessageDialog(this, "An error occurred while submitting feedback", "Error", JOptionPane.ERROR_MESSAGE);
    }
                rs.close();
                cstmt.close();
                conn.close();
                
    } catch (Exception ex) {
        ex.printStackTrace();
        // Handle SQL exception
    }
            
            
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        HOMEPAGE home=new HOMEPAGE();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        lbl_exit.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        lbl_exit.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_exitMouseExited

    private void lbl_BookBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseClicked
        PassBookBus bookBus=new PassBookBus(id);
        bookBus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_BookBusMouseClicked

    private void lbl_BookBusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseEntered

        lbl_BookBus.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_BookBusMouseEntered

    private void lbl_BookBusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BookBusMouseExited
        lbl_BookBus.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_BookBusMouseExited

    private void lbl_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseClicked
        PassPayment payment= new PassPayment(id);
        payment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_paymentMouseClicked

    private void lbl_paymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseEntered
        lbl_payment.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_paymentMouseEntered

    private void lbl_paymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentMouseExited
        lbl_payment.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_paymentMouseExited

    private void lbl_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseClicked
        PassTicket ticket=new PassTicket(id);
        ticket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_ticketMouseClicked

    private void lbl_ticketMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseEntered
        lbl_ticket.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ticketMouseEntered

    private void lbl_ticketMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticketMouseExited
        lbl_ticket.setForeground(new Color(255,255,255));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ticketMouseExited

    private void lbl_profleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseClicked
        PassProfile pro=new PassProfile(id);
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_profleMouseClicked

    private void lbl_profleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseEntered
        lbl_profle.setForeground(new Color(0,0,0));        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_profleMouseEntered

    private void lbl_profleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_profleMouseExited
        lbl_profle.setForeground(new Color(255,255,255));
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_profleMouseExited

    private void lbl_addEmployee1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseClicked
        PassFeedBack feed=new PassFeedBack(id);
        feed.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_addEmployee1MouseClicked

    private void lbl_addEmployee1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseEntered
        lbl_addEmployee1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_addEmployee1MouseEntered

    private void lbl_addEmployee1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addEmployee1MouseExited
        lbl_addEmployee1.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_lbl_addEmployee1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassFeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassFeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassFeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassFeedBack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassFeedBack(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cmb_rating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_BookBus;
    private javax.swing.JLabel lbl_addEmployee1;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_payment;
    private javax.swing.JLabel lbl_profle;
    private javax.swing.JLabel lbl_ticket;
    private javax.swing.JTextArea txt_comm;
    private javax.swing.JTextField txt_dest;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fare;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_seatNo;
    private javax.swing.JTextField txt_source;
    // End of variables declaration//GEN-END:variables
}
