/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busticketmanagement;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Asghar Qambar Rizvi
 */
public class UpdateSchedule extends javax.swing.JFrame {

    /**
     * Creates new form UpdateSchedule
     */
    AdminAddSch addSch = new AdminAddSch(username);
    static String scheduleId,routeId,busId,departureTime,arrivalTime,fare,username;
    public UpdateSchedule(String scheduleId,String routeId,String busId,String departureTime,String arrivalTime,String fare,String username) {
        initComponents();
        this.scheduleId=scheduleId;
        this.routeId=routeId;
        this.busId=busId;
        this.departureTime=departureTime;
        this.arrivalTime=arrivalTime;
        this.fare=fare;
        cmb_busID.addItem(busId);
        cmb_routeId.addItem(routeId);
        addSch.populateBusComboBox();
        addSch.populateRouteComboBox();
        this.username=username;
        display();
    }
    
    class JpanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height= getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            GradientPaint gp= new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    private void display(){
        txt_arrivalTime.setText(arrivalTime);
        txt_departureTime.setText(departureTime);
        txt_fare.setText(fare);
        cmb_busID.setSelectedIndex(1);
        cmb_routeId.setSelectedIndex(1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new JpanelGradient();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_arrivalTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_departureTime = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmb_busID = new javax.swing.JComboBox<>();
        cmb_routeId = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txt_fare = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("S E L E C T   A   R O U T  E   I D :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("A R R I V A L  D A T E   A N D   T I M E :");

        txt_arrivalTime.setBackground(new Color(0,0,0,0));
        txt_arrivalTime.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_arrivalTime.setForeground(new java.awt.Color(255, 255, 255));
        txt_arrivalTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("U P D A T E");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_departureTime.setBackground(new Color(0,0,0,0));
        txt_departureTime.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_departureTime.setForeground(new java.awt.Color(255, 255, 255));
        txt_departureTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txt_departureTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_departureTimeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("D E P A R T U R E  D A T E   A N D   T I M E :");

        cmb_busID.setBackground(new Color(0,0,0,0));
        cmb_busID.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cmb_busID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[- SELECT ONE-]" }));
        cmb_busID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        cmb_routeId.setBackground(new Color(0,0,0,0));
        cmb_routeId.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        cmb_routeId.setForeground(new java.awt.Color(255, 255, 255));
        cmb_routeId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[- SELECT ONE-]" }));
        cmb_routeId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        cmb_routeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_routeIdActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("E N T E R   F A I R  :");

        txt_fare.setBackground(new Color(0,0,0,0));
        txt_fare.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        txt_fare.setForeground(new java.awt.Color(255, 255, 255));
        txt_fare.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("S E L E C T   A   B U S   I D : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_routeId, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(202, 202, 202)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_busID, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_departureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(172, 172, 172)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_busID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_routeId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(9, 9, 9)
                        .addComponent(txt_departureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_arrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel19))
                .addGap(150, 150, 150))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkTimes(String departureDateTime, String arrivalDateTime) {
        try {
            // Define the date format
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S");
            dateFormat.setLenient(false);
            
            // Parse the input dates and times
            Date parsedDepartureDate = dateFormat.parse(departureDateTime);
            java.sql.Timestamp departureTimestamp = new java.sql.Timestamp(parsedDepartureDate.getTime());
            
            Date parsedArrivalDate = dateFormat.parse(arrivalDateTime);
            java.sql.Timestamp arrivalTimestamp = new java.sql.Timestamp(parsedArrivalDate.getTime());
            
            // Get the current date and time
            Date currentDate = new Date();
            java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(currentDate.getTime());
            
            // Compare the parsed dates with the current date
            if (departureTimestamp.before(currentTimestamp)) {
                // Show error message if the departure date is before the current date
                JOptionPane.showMessageDialog(null, "Error: The departure time cannot be in the past.");
                return false; // Exit the method
            }
            
            if (arrivalTimestamp.before(currentTimestamp)) {
                // Show error message if the arrival date is before the current date
                JOptionPane.showMessageDialog(null, "Error: The arrival time cannot be in the past.");
                return false; // Exit the method
            }
            
            if (arrivalTimestamp.before(departureTimestamp)) {
                // Show error message if the arrival time is before the departure time
                JOptionPane.showMessageDialog(null, "Error: The arrival time cannot be before the departure time.");
                return false; // Exit the method
            }
            
            // Continue with the processing if both dates are valid
            JOptionPane.showMessageDialog(null, "The departure and arrival times are valid.");
            return true;
            // Further processing...

        } catch (Exception e) {
            // Show error message if parsing fails
            JOptionPane.showMessageDialog(null, "Error: Invalid date format. Please enter the dates in 'yyyy-MM-dd HH:mm:ss.S' format.");
            return false;
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String departureTime = txt_departureTime.getText();
        String arrivalTime = txt_arrivalTime.getText();
        String busId = cmb_busID.getSelectedItem().toString();
        int routeId = Integer.parseInt(cmb_routeId.getSelectedItem().toString());
        float fare = Float.parseFloat(txt_fare.getText()); 
        int scheduleID = Integer.parseInt(scheduleId);
        if (departureTime.isEmpty() || arrivalTime.isEmpty() || busId.isEmpty() || txt_fare.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!checkTimes(departureTime, arrivalTime)) {
             
            }
            else{
            try {
                // Connect to the database
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                try (Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=mydatabase;encrypt=true;trustServerCertificate=true", "admin", "123456");
                     CallableStatement cstmt = conn.prepareCall("{call UpdateSchedule(?, ?, ?, ?, ?,?)}")) {
                    cstmt.setInt(1, scheduleID);
                    cstmt.setInt(2, routeId);
                    cstmt.setString(3, busId);
                    cstmt.setString(4, departureTime);
                    cstmt.setString(5, arrivalTime);
                    cstmt.setFloat(6, fare);

                    // Execute the stored procedure
                    int rowsUpdated = cstmt.executeUpdate();
                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(null, "Schedule updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        dispose(); // Close the current frame
                        AdminAddSch addSch = new AdminAddSch(username);
                        addSch.setVisible(true); // Open a new AdminAddSch frame
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to update schedule", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (Exception e) {
                // Log the exception or show a generic error message
                JOptionPane.showMessageDialog(null, "An error occurred while updating the schedule", "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace(); // Log the exception
            }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_departureTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_departureTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_departureTimeActionPerformed

    private void cmb_routeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_routeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_routeIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSchedule(scheduleId,routeId,busId,departureTime,arrivalTime,fare,username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_busID;
    private javax.swing.JComboBox<String> cmb_routeId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_arrivalTime;
    private javax.swing.JTextField txt_departureTime;
    private javax.swing.JTextField txt_fare;
    // End of variables declaration//GEN-END:variables
}
